apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsolferreira/minikube_lab.git
    targetRevision: main
    path: charts/mtapp
    #helm:
    #  valueFiles:
    #    - envs/dev/myapp-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true